server:
  port: 8082

spring:
  application:
    name: restaurant-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
